backend:
  name: github
  repo: speexy/gatsby-boilerplate
  branch: master # Branch to update (optional; defaults to master)

media_folder: "ui/static/media" # Media files will be stored in the repo under images/uploads
public_folder: /media


collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/index.md"
        label: "Home"
        name: "index"
        fields:
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Body", name: "body", widget: "markdown"}
      - file: "content/blog.md"
        label: "Blog"
        name: "blog"
        fields:
            - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog"}
            - {label: "Title", name: "title", widget: "string"}
            - {label: "Body", name: "body", widget: "markdown"}
  - name: "posts"
    label: "Posts"
    folder: "content/blog"
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "markdown", pattern: ['^.{0,350}$', "Must have between 0 and 350 characters"] }
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
